spring.application.name=springdemo
spring-demo-order=http://localhost:8081/orders

spring.datasource.url=jdbc:postgresql://172.16.1.195:5331/dbdemo
spring.datasource.username=dbuser
spring.datasource.password=yF2awnXt
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

